PREFIX rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
PREFIX owl: http://www.w3.org/2002/07/owl#

SELECT ?class (group_concat(DISTINCT ?item;separator=",") as ?keys) WHERE {
  ?class rdf:type owl:Class .
  ?class owl:hasKey ?key .
  ?key rdf:rest*/rdf:first ?item .
}
GROUP BY ?class ?key
