PREFIX : <http://bigdata.com>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX ex:  <http://example.org/>

CONSTRUCT {
  ?bob foaf:name "Bob" .
  <<?bob foaf:age ?age>> ?b ?c .
}
WHERE {
  ?bob foaf:name "Bob" .
  <<?bob foaf:age ?age>> ?b ?c .
}
