PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?id ?adjusted WHERE {
	VALUES (?id ?tz ?d) {
		(1 "-PT10H"^^xsd:dayTimeDuration "10:00:00"^^xsd:time)
		(2 "-PT10H"^^xsd:dayTimeDuration "10:00:00-07:00"^^xsd:time)
		(3 "PT10H"^^xsd:dayTimeDuration"10:00:00-07:00"^^xsd:time)
		(4 "" "10:00:00"^^xsd:time)
		(5 "" "10:00:00-07:00"^^xsd:time)
	}
	BIND(ADJUST(?d, ?tz) AS ?adjusted)
}
