PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT (xsd:duration(?literal) AS ?duration) WHERE {
	VALUES ?literal {
		"PT0S"
		"-P0M"
		"P1Y"
		"-P1Y"
		"P1M"
		"P1D"
		"PT1H"
		"PT1M"
		"PT1S"
		"P3Y1DT2H7S"
		"P36MT120M"
	}
}
