PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT (?l - ?r AS ?duration)
WHERE {
	VALUES (?l ?r) {
		("2000-10-30T06:12:00-05:00"^^xsd:dateTime "1999-11-28T09:00:00Z"^^xsd:dateTime)
		("2000-10-30"^^xsd:date                    "1999-11-28"^^xsd:date)
		("11:12:00Z"^^xsd:time                     "04:00:00-05:00"^^xsd:time)
	}
}
