PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT (?d - ?duration AS ?datetime)
WHERE {
	VALUES (?duration ?d) {
		("P3DT1H15M"^^xsd:dayTimeDuration "2000-10-30T11:12:00"^^xsd:dateTime)
		("P3DT1H15M"^^xsd:dayTimeDuration "2000-10-30"^^xsd:date)
		("P3DT1H15M"^^xsd:dayTimeDuration "11:12:00"^^xsd:time)
	}
}
