PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT (?d - ?duration AS ?year_ago)
WHERE {
	VALUES (?duration ?d) {
		("P1Y"^^xsd:yearMonthDuration "2019-05-28T12:14:45Z"^^xsd:dateTime)
		("P1Y"^^xsd:yearMonthDuration "2019-05-28"^^xsd:date)
	}
}
